services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    hostname: redis-master
    ports:
      - '6379:6739'
    volumes:
      - redis-master-data:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      # - ./aclfile.acl:/usr/local/etc/redis/aclfile.acl
    command: [
        'redis-server',
        '/usr/local/etc/redis/redis.conf',
        # '--appendonly',
        # 'yes',
        # '--repl-diskless-load',
        # 'on-empty-db',
        # '--replica-announce-ip',
        # '${HOST_IP}',
        # '--replica-announce-port',
        # '6379',
        # '--protected-mode',
        # 'no',
        # if not using acl file, comment out the following line
        # '--requirepass',
        # 'Complex-Password-Goes-Here',
        # '--aclfile',
        # '/usr/local/etc/redis/aclfile.acl',
      ]
    networks:
      redis-net:
        ipv4_address: 172.21.0.3

  redis-slave-1:
    image: redis:latest
    container_name: redis-slave-1
    hostname: redis-slave-1
    depends_on:
      - redis-master
    ports:
      - '6380:6379'
    volumes:
      - redis-slave1-data:/data
      - ./conf/redis-slave-1.conf:/usr/local/etc/redis/redis.conf
      # - ./aclfile.acl:/usr/local/etc/redis/aclfile.acl
    command: [
        'redis-server',
        '/usr/local/etc/redis/redis.conf',
        # '--appendonly',
        # 'yes',
        # '--replicaof',
        # 'redis-master 6379',
        # '--repl-diskless-load',
        # 'on-empty-db',
        # '--replica-announce-ip',
        # '${HOST_IP}',
        # '--replica-announce-port',
        # '6380',
        # '--protected-mode',
        # 'no',
        # if not using acl file, comment out the following line
        # '--requirepass',
        # 'Complex-Password-Goes-Here',
        # '--masterauth',
        # '${REDIS_MASTER_PASSWORD}',
        # '--aclfile',
        # '/usr/local/etc/redis/aclfile.acl',
      ]
    networks:
      redis-net:
        ipv4_address: 172.21.0.4

  redis-slave-2:
    image: redis:latest
    container_name: redis-slave-2
    hostname: redis-slave-2
    depends_on:
      - redis-master
    ports:
      - '6381:6379'
    volumes:
      - redis-slave2-data:/data
      - ./conf/redis-slave-2.conf:/usr/local/etc/redis/redis.conf
      # - ./aclfile.acl:/usr/local/etc/redis/aclfile.acl
    command: [
        'redis-server',
        '/usr/local/etc/redis/redis.conf',
        # '--appendonly',
        # 'yes',
        # '--replicaof',
        # 'redis-master 6379',
        # '--repl-diskless-load',
        # 'on-empty-db',
        # '--replica-announce-ip',
        # '${HOST_IP}',
        # '--replica-announce-port',
        # '6381',
        # '--protected-mode',
        # 'no',
        # if not using acl file, comment out the following line
        # '--requirepass',
        # 'Complex-Password-Goes-Here',
        # '--masterauth',
        # '${REDIS_MASTER_PASSWORD}',
        # '--aclfile',
        # '/usr/local/etc/redis/aclfile.acl',
      ]
    networks:
      redis-net:
        ipv4_address: 172.21.0.5

  sentinel-1:
    image: redis:latest
    container_name: sentinel-1
    hostname: sentinel-1
    depends_on:
      - redis-master
    ports:
      - '${SENTINEL_PORT_1}:26379'
    # volumes:
    #   - ./sentinel-data-1:/data
    #   - ./conf/sentinel-1.conf:/etc/sentinel.conf
    # command: ['redis-sentinel', '/etc/sentinel.conf']
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
            echo "sentinel monitor ${REDIS_CLUSTER_NAME} 172.21.0.3 6379 2" >> /etc/sentinel.conf &&
            echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds ${REDIS_CLUSTER_NAME} 10000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout ${REDIS_CLUSTER_NAME} 10000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs ${REDIS_CLUSTER_NAME} 1" >> /etc/sentinel.conf &&
            redis-sentinel /etc/sentinel.conf'
    networks:
      redis-net:
        ipv4_address: 172.21.0.6

  sentinel-2:
    image: redis:latest
    container_name: sentinel-2
    hostname: sentinel-2
    depends_on:
      - redis-master
    ports:
      - '${SENTINEL_PORT_2}:26379'
    # volumes:
    #   - ./sentinel-data-2:/data
    #   - ./conf/sentinel-2.conf:/etc/sentinel.conf
    # command: ['redis-sentinel', '/etc/sentinel.conf']
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
            echo "sentinel monitor ${REDIS_CLUSTER_NAME} 172.21.0.3 6379 2" >> /etc/sentinel.conf &&
            echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds ${REDIS_CLUSTER_NAME} 10000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout ${REDIS_CLUSTER_NAME} 10000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs ${REDIS_CLUSTER_NAME} 1" >> /etc/sentinel.conf &&
            redis-sentinel /etc/sentinel.conf'
    networks:
      redis-net:
        ipv4_address: 172.21.0.7

  sentinel-3:
    image: redis:latest
    container_name: sentinel-3
    hostname: sentinel-3
    depends_on:
      - redis-master
    ports:
      - '${SENTINEL_PORT_3}:26379'
    # volumes:
    #   - ./sentinel-data-3:/data
    #   - ./conf/sentinel-3.conf:/etc/sentinel.conf
    # command: ['redis-sentinel', '/etc/sentinel.conf']
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
            echo "sentinel monitor ${REDIS_CLUSTER_NAME} 172.21.0.3 6379 2" >> /etc/sentinel.conf &&
            echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds ${REDIS_CLUSTER_NAME} 10000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout ${REDIS_CLUSTER_NAME} 10000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs ${REDIS_CLUSTER_NAME} 1" >> /etc/sentinel.conf &&
            redis-sentinel /etc/sentinel.conf'
    networks:
      redis-net:
        ipv4_address: 172.21.0.8

networks:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  redis-master-data:
  redis-slave1-data:
  redis-slave2-data:
